version: '3'

services:
  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENER: INSIDE_KAFKA:9093
      KAFKA_LISTENER: INSIDE_KAFKA:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  tensorflow-serving:
    image: tensorflow/serving
    ports:
      - "8501:8501"
    volumes:
      - ./models:/models
    environment:
      - MODEL_NAME=sales_model
    depends_on:
      - kafka  # Ensure Kafka is up before starting TensorFlow Serving

  faust-consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    depends_on:
      - kafka
      - tensorflow-serving
    command: python consumer/kafka_streams.py  # Automatically run the Faust Consumer

  kafka-producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    depends_on:
      - kafka
    command: python producer/kafka_producer.py  # Automatically run the Kafka Producer


