FROM python:3.8-slim

# Set the working directory
WORKDIR /app

# Install Kafka Python library
RUN pip install confluent_kafka

# Copy the producer script
COPY producer/kafka_producer.py /app/

# Run the producer script when the container starts
CMD ["python", "kafka_producer.py"]
